# Generated by Django 4.1.3 on 2022-12-04 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_groupprofits_user_alter_groupspending_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupprofits",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
